[2023-11-30T18:12:48.282+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T13:11:29.224591+00:00 [queued]>
[2023-11-30T18:12:48.340+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T13:11:29.224591+00:00 [queued]>
[2023-11-30T18:12:48.341+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T18:12:48.427+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 13:11:29.224591+00:00
[2023-11-30T18:12:48.430+0500] {standard_task_runner.py:57} INFO - Started process 4984 to run task
[2023-11-30T18:12:48.440+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'train_model', 'manual__2023-11-30T13:11:29.224591+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmptz21wax4']
[2023-11-30T18:12:48.441+0500] {standard_task_runner.py:85} INFO - Job 41: Subtask train_model
[2023-11-30T18:12:48.561+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.train_model manual__2023-11-30T13:11:29.224591+00:00 [running]> on host debian
[2023-11-30T18:12:48.718+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T13:11:29.224591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T13:11:29.224591+00:00'
[2023-11-30T18:12:48.721+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T18:12:48.722+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/train_model.py']
[2023-11-30T18:12:48.753+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T18:13:07.085+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T18:13:07.095+0500] {subprocess.py:93} INFO - 
[2023-11-30T18:13:07.095+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T18:13:07.095+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T18:13:07.117+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T18:13:07.118+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T18:13:07.118+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T18:13:31.987+0500] {subprocess.py:93} INFO - Registered model 'model' already exists. Creating a new version of this model...
[2023-11-30T18:13:32.121+0500] {subprocess.py:93} INFO - 2023/11/30 18:13:32 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: model, version 4
[2023-11-30T18:13:32.121+0500] {subprocess.py:93} INFO - Created version '4' of model 'model'.
[2023-11-30T18:13:33.143+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T18:13:33.203+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=regression_score, task_id=train_model, execution_date=20231130T131129, start_date=20231130T131248, end_date=20231130T131333
