[2023-11-30T17:50:51.366+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T12:50:13.287014+00:00 [queued]>
[2023-11-30T17:50:51.375+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T12:50:13.287014+00:00 [queued]>
[2023-11-30T17:50:51.375+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T17:50:51.428+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 12:50:13.287014+00:00
[2023-11-30T17:50:51.436+0500] {standard_task_runner.py:57} INFO - Started process 3479 to run task
[2023-11-30T17:50:51.455+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'train_model', 'manual__2023-11-30T12:50:13.287014+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmp0gdxbu1d']
[2023-11-30T17:50:51.480+0500] {standard_task_runner.py:85} INFO - Job 25: Subtask train_model
[2023-11-30T17:50:51.571+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.train_model manual__2023-11-30T12:50:13.287014+00:00 [running]> on host debian
[2023-11-30T17:50:51.702+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T12:50:13.287014+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T12:50:13.287014+00:00'
[2023-11-30T17:50:51.702+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T17:50:51.703+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/train_model.py']
[2023-11-30T17:50:51.725+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T17:51:01.212+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T17:51:01.243+0500] {subprocess.py:93} INFO - 
[2023-11-30T17:51:01.243+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T17:51:01.243+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T17:51:01.248+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T17:51:01.248+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T17:51:01.248+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T17:51:01.796+0500] {subprocess.py:93} INFO - 2023/11/30 17:51:01 INFO mlflow.tracking.fluent: Experiment with name 'model_training' does not exist. Creating a new experiment.
[2023-11-30T17:52:35.247+0500] {subprocess.py:93} INFO - Successfully registered model 'model'.
[2023-11-30T17:52:35.409+0500] {subprocess.py:93} INFO - 2023/11/30 17:52:35 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: model, version 1
[2023-11-30T17:52:35.413+0500] {subprocess.py:93} INFO - Created version '1' of model 'model'.
[2023-11-30T17:52:36.726+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T17:52:36.934+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=regression_score, task_id=train_model, execution_date=20231130T125013, start_date=20231130T125051, end_date=20231130T125236
