[2023-11-30T18:10:13.359+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.test_model manual__2023-11-30T13:06:17.923217+00:00 [queued]>
[2023-11-30T18:10:13.382+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.test_model manual__2023-11-30T13:06:17.923217+00:00 [queued]>
[2023-11-30T18:10:13.382+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T18:10:13.446+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_model> on 2023-11-30 13:06:17.923217+00:00
[2023-11-30T18:10:13.452+0500] {standard_task_runner.py:57} INFO - Started process 4951 to run task
[2023-11-30T18:10:13.464+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'test_model', 'manual__2023-11-30T13:06:17.923217+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmp7gykemr8']
[2023-11-30T18:10:13.466+0500] {standard_task_runner.py:85} INFO - Job 37: Subtask test_model
[2023-11-30T18:10:13.603+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.test_model manual__2023-11-30T13:06:17.923217+00:00 [running]> on host debian
[2023-11-30T18:10:13.751+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T13:06:17.923217+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T13:06:17.923217+00:00'
[2023-11-30T18:10:13.758+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T18:10:13.758+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/test_model.py']
[2023-11-30T18:10:13.780+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T18:10:24.196+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T18:10:24.223+0500] {subprocess.py:93} INFO - 
[2023-11-30T18:10:24.223+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T18:10:24.223+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T18:10:24.239+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T18:10:24.239+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T18:10:24.239+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T18:10:26.140+0500] {subprocess.py:93} INFO - RMSE = 4.368135918399492
[2023-11-30T18:10:26.141+0500] {subprocess.py:93} INFO - MAE = 3.5325896724374415
[2023-11-30T18:10:26.141+0500] {subprocess.py:93} INFO - R2 = 0.6907840669049515
[2023-11-30T18:10:28.363+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T18:10:28.447+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=regression_score, task_id=test_model, execution_date=20231130T130617, start_date=20231130T131013, end_date=20231130T131028
[2023-11-30T18:10:28.556+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T18:10:28.569+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
