[2023-11-30T18:18:07.465+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.test_model manual__2023-11-30T13:11:29.224591+00:00 [queued]>
[2023-11-30T18:18:07.484+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.test_model manual__2023-11-30T13:11:29.224591+00:00 [queued]>
[2023-11-30T18:18:07.484+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T18:18:07.533+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_model> on 2023-11-30 13:11:29.224591+00:00
[2023-11-30T18:18:07.538+0500] {standard_task_runner.py:57} INFO - Started process 5951 to run task
[2023-11-30T18:18:07.548+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'test_model', 'manual__2023-11-30T13:11:29.224591+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmpvqkpe87g']
[2023-11-30T18:18:07.555+0500] {standard_task_runner.py:85} INFO - Job 43: Subtask test_model
[2023-11-30T18:18:07.652+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.test_model manual__2023-11-30T13:11:29.224591+00:00 [running]> on host debian
[2023-11-30T18:18:08.010+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T13:11:29.224591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T13:11:29.224591+00:00'
[2023-11-30T18:18:08.043+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T18:18:08.047+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/test_model.py']
[2023-11-30T18:18:08.126+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T18:18:26.368+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T18:18:26.658+0500] {subprocess.py:93} INFO - 
[2023-11-30T18:18:26.659+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T18:18:26.663+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T18:18:26.668+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T18:18:26.668+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T18:18:26.668+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T18:18:44.132+0500] {subprocess.py:93} INFO - RMSE = 3.772048015052277
[2023-11-30T18:18:44.294+0500] {subprocess.py:93} INFO - MAE = 3.1564641444459545
[2023-11-30T18:18:44.297+0500] {subprocess.py:93} INFO - R2 = 0.7789304959716352
[2023-11-30T18:18:54.891+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T18:18:55.209+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=regression_score, task_id=test_model, execution_date=20231130T131129, start_date=20231130T131807, end_date=20231130T131855
[2023-11-30T18:18:55.487+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T18:18:55.529+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
