[2023-11-30T17:18:11.798+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T12:11:22.568705+00:00 [queued]>
[2023-11-30T17:18:11.808+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T12:11:22.568705+00:00 [queued]>
[2023-11-30T17:18:11.809+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T17:18:11.888+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 12:11:22.568705+00:00
[2023-11-30T17:18:11.893+0500] {standard_task_runner.py:57} INFO - Started process 2217 to run task
[2023-11-30T17:18:11.916+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'train_model', 'manual__2023-11-30T12:11:22.568705+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmpk0pujqdk']
[2023-11-30T17:18:11.920+0500] {standard_task_runner.py:85} INFO - Job 21: Subtask train_model
[2023-11-30T17:18:12.035+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.train_model manual__2023-11-30T12:11:22.568705+00:00 [running]> on host debian
[2023-11-30T17:18:12.391+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T12:11:22.568705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T12:11:22.568705+00:00'
[2023-11-30T17:18:12.394+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T17:18:12.395+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/train_model.py']
[2023-11-30T17:18:12.437+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T17:18:32.767+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T17:18:32.819+0500] {subprocess.py:93} INFO - 
[2023-11-30T17:18:32.819+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T17:18:32.819+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T17:18:32.927+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T17:18:32.927+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T17:18:32.927+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T17:18:35.726+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-30T17:18:35.727+0500] {subprocess.py:93} INFO -   File "/home/flow/MLops_3/scripts/train_model.py", line 8, in <module>
[2023-11-30T17:18:35.735+0500] {subprocess.py:93} INFO -     mlflow.set_experiment("train_model")
[2023-11-30T17:18:35.750+0500] {subprocess.py:93} INFO -   File "/home/flow/MLops_3/venv/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 155, in set_experiment
[2023-11-30T17:18:35.761+0500] {subprocess.py:93} INFO -     raise MlflowException(
[2023-11-30T17:18:35.762+0500] {subprocess.py:93} INFO - mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'train_model' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.
[2023-11-30T17:18:40.763+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-30T17:18:40.921+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/flow/MLops_3/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-30T17:18:40.938+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=regression_score, task_id=train_model, execution_date=20231130T121122, start_date=20231130T121811, end_date=20231130T121840
[2023-11-30T17:18:41.186+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 2217)
[2023-11-30T17:18:41.239+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T17:18:41.324+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
